### ISSUE TITLE
Linked packages font color

### ISSUE THREAD

**Issue by GTrebaol** [adogor/npm-autolink#1]
```
npm-autolink matches
```

```
npm-autolink 
```

The font color of the linked packages for those two commands is black. Since my terminal has a black background, I can't see them.

![imageedit_2_5747586965](https://cloud.githubusercontent.com/assets/1216023/8910195/b3ef7c26-3485-11e5-80c3-4f16fa5f522e.png)

**Comment by adogor** [comment]
Hi Gwen, hope your doing well.

Colors will be fixed in 0.4.0
