### ISSUE TITLE
Remove not working for private npm packages

### ISSUE THREAD

**Issue by ThomasBormans** [adogor/npm-autolink#3]
I have a folder for all my private npm packages. Inside this folder there is a simple package.json and different folders for each package. These folders are at the same level as the package.json file, so not in another folder prepended with an _@_ (like npm does with its private packages).

I have created an .autolink file in the root of my project to symlink to this specific folder. When I run `npm-autolink link` everything works fine. However when I run `npm-autolink remove`, all the symlinks remain as they were created by _link_.

I can fix it by appending **/@username** (assuming my private npm name is **username**) behind the [nodeModulesPath](https://github.com/adogor/npm-autolink/blob/master/index.js#L270) variable in the _listLinks()_ function. This is of course not a solution but I hope it helps to solve the bug.

**Comment by adogor** [comment]
Will be fixed in 0.4.0
